# Server configuration
server.port=8080

# Database configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://thomas.proxy.rlwy.net:12205/railway?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=uxLpTfZpDdHQWufvSTZLcAMjfPKaRYek
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Secret
jwt.secret=YourSuperSecretKeyForJWTTokenGenerationWhichIsLongEnough
jwt.expiration=86400000

# EMAIL GMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mobilizatcc@gmail.com
# IMPORTANTE: Se o Gmail tiver verificação em duas etapas, você DEVE usar uma "Senha de App"
spring.mail.password=Copa123@2026
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
