# Server configuration
server.port=8080

# Database configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://thomas.proxy.rlwy.net:12205/railway
spring.datasource.username=postgres
spring.datasource.password=uxLpTfZpDdHQWufvSTZLcAMjfPKaRYek
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Secret
jwt.secret=YourSuperSecretKeyForJWTTokenGenerationWhichIsLongEnough
jwt.expiration=86400000
